yolo_model:

  config_file:
    name: yolov3-tiny-two-objects.cfg
  weight_file:
    name: yolov3-tiny-plant_counter.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - plant
      - counter
