yolo_model:

  config_file:
    name: yolov3-tiny-one-object.cfg
  weight_file:
    name: yolov3-tiny-only_suitcase.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - suitcase
